name: Sync và Backup

on:
  schedule:
    - cron: '0 18 * * *'
  workflow_dispatch:

jobs:
  sync-backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_PAT }}
          fetch-depth: 0

      - name: Sync và Backup từ action private
        uses: tuthanika/ATP-Sync-and-Backup@main
        with:
          env-file: repo.env
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          # Bạn có thể override bất kỳ biến nào ở đây, ví dụ:
          #GIT_USER_NAME: ${{ secrets.GIT_USER_NAME }}
          #GIT_USER_EMAIL: ${{ secrets.GIT_USER_EMAIL }}
          #UPSTREAM_URL: ${{ secrets.UPSTREAM_URL }}
          #SOURCE_BRANCH_MANUAL: ${{ secrets.SOURCE_BRANCH_MANUAL }}
          #TARGET_BRANCH_MANUAL: ${{ secrets.TARGET_BRANCH_MANUAL }}
          #BACKUP_BRANCH: ${{ secrets.BACKUP_BRANCH }}  
          #BACKUP_AUTHOR: ${{ secrets.BACKUP_AUTHOR }}
          #BACKUP_PATHS: ${{ secrets.BACKUP_PATHS }}
          #REPLACE_RULES_1: ${{ secrets.REPLACE_RULES_1 }}
          #REPLACE_RULES_2: ${{ secrets.REPLACE_RULES_2 }}
          